contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #crispresso channel"
    url: https://nfcore.slack.com/channels/crispresso
    about: Discussion about the nf-core/crispresso pipeline
